name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate proto code
        run: buf generate

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: '6.0.5'

      - name: Execute GitVersion
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.1.1
        with:
          useConfigFile: true

      - name: Create Git Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ steps.version_step.outputs.GitVersion_MajorMinorPatch }}

      - name: Push Tag
        run: git push origin v${{ steps.version_step.outputs.GitVersion_MajorMinorPatch }}
